config/routes.rb
Rails.application.routes.draw do
  resources :hack_boxes
  root to: "hack_boxes#all"

end

app/models/hack_box.rb
class HackBox < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hack_boxes_controller.rb
class HackBoxesController < ApplicationController
    def all
=begin
      GoogleSpreadsheet.config do |c|
        c.email               = "cwealthcraft@gmail.com"
        c.password            = "G_linux69linux"

        # optional, see note below on how to obtain a spreadsheet key
        c.default_spreadsheet = "1Jm6q8PQ415ayzXwsd57sePG6a29ijhSw-ZwReHiqgZ0"
      end

      [
        {:name => "Bob", :age => 26}, 
        {:name => "John", :age => 28}
      ].to_google_spreadsheet("Sheet1")
=end

      # Configure
      GoogleSpreadsheet.config do |c|
        c.email               = "cwealthcraft@gmail.com"
        c.password            = "G_linux69linux"

        # optional, see note below on how to obtain a spreadsheet key
        c.default_spreadsheet = "1Jm6q8PQ415ayzXwsd57sePG6a29ijhSw-ZwReHiqgZ0"
      end

      # Populates the worksheet "Employees" in the default spreadsheet 
      # with two employees
      [
        {:name => "Brian", :age => 26}, 
        {:name => "Dave B", :age => 28}
      ].to_google_spreadsheet("Employees")

      # Populates the worksheet "Signups" in the nondefault spreadsheet 
      # with two signup dates
      [
        {:date => "18/7/2011", :signups => 28},
        {:date => "19/7/2011", :signups => 33}
      ].to_google_spreadsheet("Signups", "1Jm6q8PQ415ayzXwsd57sePG6a29ijhSw-ZwReHiqgZ0")

      # Populates the worksheet "Accounts" in the default spreadsheet 
      # with all # accounts in the database
      #Account.all.to_google_spreadsheet("Accounts")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hack_boxes_helper.rb
module HackBoxesHelper
end

app/views/hack_boxes/_form.html.erb
<%= form_for(@hack_box) do |f| %>
  <% if @hack_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hack_box.errors.count, "error") %> prohibited this hack_box from being saved:</h2>

      <ul>
      <% @hack_box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hack_boxes/all.html.erb
<p> Goddam work!!! </p>

app/views/hack_boxes/edit.html.erb
<h1>Editing hack_box</h1>

<%= render 'form' %>

<%= link_to 'Show', @hack_box %> |
<%= link_to 'Back', hack_boxes_path %>

app/views/hack_boxes/index.html.erb
<h1>Listing hack_boxes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hack_boxes.each do |hack_box| %>
      <tr>
        <td><%= link_to 'Show', hack_box %></td>
        <td><%= link_to 'Edit', edit_hack_box_path(hack_box) %></td>
        <td><%= link_to 'Destroy', hack_box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hack box', new_hack_box_path %>

app/views/hack_boxes/new.html.erb
<h1>New hack_box</h1>

<%= render 'form' %>

<%= link_to 'Back', hack_boxes_path %>

app/views/hack_boxes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hack_box_path(@hack_box) %> |
<%= link_to 'Back', hack_boxes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoxApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>